apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
    service: app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
  #type: ClusterIP
  selector:
    app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: rojcosta/lab-teste-dev:1
        #image: image-replace
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-replace
spec:
  ingressClassName: nginx
  rules:
  - host: ingress-replace.poc.ms.qa
    http:
      paths:
      - backend:
          service:
            name: app
            port:
              number: 8080
        path: /
        pathType: Prefix
