management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: "info,health,prometheus"
      path-mapping:
        prometheus: metrics

info:
  app:
    name: "Sirius"
    description: "Poc Java code!"
    version: "0.0.3"