apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
    app: httpd
    service: httpd
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  type: NodePort
  selector:
    app: httpd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpd
  labels:
    account: httpd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      serviceAccountName: httpd-service-account
      containers:
      - name: httpd
        image: httpd
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15